<?php
/**
 * Created by PhpStorm.
 * User: MengYi
 * Date: 2018/8/21
 * Time: 13:39
 */

namespace app\modules\m\controllers\common;
use app\common\components\BaseWebController;

class BaseController extends BaseWebController{



    public function beforeAction($action)
    {

        return parent::beforeAction($action); // TODO: Change the autogenerated stub

    }


    public function __construct($id,  $module, array $config = [])
    {

    parent::__construct($id, $module, $config);

    }




}